FOT-Group-Project/Sabaragamu-Athsalu-Management-System

api/controllers/auth.controller.js, api/index.js, api/models/user.models.js, api/routes/auth.route.js, api/utils/error.js, client/src/components/Header.jsx, client/src/pages/SignIn.jsx, client/src/pages/SignUp.jsx, client/vite.config.js, package-lock.json, package.json
I completed user Login functionality.
=> Maleesha user authentication

client/package-lock.json, client/package.json, client/src/components/DashProducts.jsx, client/src/components/DashProfile.jsx, client/src/components/DashShops.jsx, client/src/components/DashSidebar.jsx, client/src/components/DashStores.jsx, client/src/components/DashUsers.jsx, client/src/firebase.js, client/src/pages/Dashboard.jsx
Maleesha create dashboard sliderbar
=> Maleesha create dashboard sliderbar

api/controllers/user.controller.js, api/routes/user.route.js, client/src/components/DashSidebar.jsx, client/src/components/Header.jsx, client/src/redux/user/userSlice.js
Add signout functionality to user controller and routes
=> Add signout functionality to user controller and routes

api/controllers/product.controller.js, api/index.js, api/routes/products.route.js
=> Product Management

api/controllers/product.controller.js, api/models/store.js, api/routes/products.route.js, client/src/components/DashProducts.jsx
Connect All the back end api to the front end
=> Pathum product management

api/controllers/association.controller.js, api/index.js, api/models/accountant.js, api/models/admin.js, api/models/customer.js, api/models/director.js, api/models/qualityassurance.js, api/models/seller.js, api/models/shop.js, api/models/storekeeper.js, api/models/user.js, api/routes/association.route.js
=> Pathum association

api/controllers/salesReport.controller.js, api/models/customerbuyitem.js
=> Add associations between CustomerBuyItem and User, Shop, and Product models

client/src/components/DashSalesReport.jsx
Refactor DashSalesReport component to update sales report title and improve search functionality added summery
=> Refactor DashSalesReport component to update sales report title and improve search functionality added summery

api/controllers/salesReport.controller.js
=> Refactor save function in salesReport.controller.js to use 'sales' key instead of 'data' in the response

client/src/components/DashSalesReport.jsx
=> Refactor DashSalesReport component to export sales report to Excel and add current date to the file name

client/src/components/DashboardComp.jsx
=> Refactor DashboardComp component to fetch sales data and calculate total sale amount

client/src/components/DashboardComp.jsx
=> Refactor DashboardComp component to calculate total sale amount and income today

client/src/components/DashboardComp.jsx
=> Refactor DashboardComp component to include total income last month and total income last day

client/package-lock.json, client/package.json, client/src/components/DashboardComp.jsx
=> Add chart.js as a dependency in package.json and package-lock.json and add sales overview pie chart

client/src/components/DashboardComp.jsx
=> Refactor DashboardComp component and ADD Monthly Sales and Customer Data chart

client/src/components/DashSaleHistory.jsx
=> chore: Refactor DashSaleHistory.jsx to improve exporting and printing functionality

client/src/components/DashSaleHistory.jsx
=> chore: Refactor DashSaleHistory.jsx to handle search functionality, improve searching using date and search query

api/controllers/storeitem.controller.js, api/controllers/storekeepermanagestore.controller.js, api/index.js, api/models/storeitem.js, api/models/storekeepermanagestore.js, api/routes/storeitem.route.js, api/routes/storekeepermanagestore.route.js, client/src/components/storeKeeper/DashStoreKeeperProducts.jsx
This commit adds the necessary routes and controller functions for performing CRUD operations on StoreItem entities. The routes include endpoints for retrieving store items by store keeper ID, retrieving a specific store item by ID, sending a store item to a shop, updating a store item, deleting a store item, and adding a new store item. These additions enable the management of store items in the application.
=> feat: Add StoreItem routes and controller for CRUD operations

client/src/components/seller/DashCustomerReturnItem.jsx
This commit adds functionality to fetch and display customer return items in the `DashCustomerReturnItem` component. The code includes the implementation of `fetchReturnItems` and `fetchReturnItemsbyShopId` functions to retrieve return items from the API based on the user's role. The component now fetches return items for the admin role and fetches return items specific to the seller's shop. This enhancement allows sellers to manage and process return requests from customers effectively.
=> feat: Fetch and display customer return items based on user role

client/src/components/seller/DashCustomerReturnItem.jsx
The code changes in this commit improve the UI of the customer return item dashboard. The "Add Returns" button now has a red background color to make it more prominent. Additionally, the table rows in the return item list now have a white background and a dark border for better visibility. These UI enhancements enhance the user experience and make it easier for sellers to manage and process return requests from customers.
=> feat: Improve customer return item dashboard UI 

client/src/components/seller/DashCustomerReturnItem.jsx
=> feat: Add modal for adding return items in customer return item dashboard

client/package-lock.json, client/package.json, client/src/components/DashSaleHistory.jsx, client/src/components/seller/DashCustomerReturnItem.jsx
This commit adds the "react-select" dependency to the project's package.json file. The "react-select" library provides dropdown functionality, which will be used in the customer return item dashboard to implement a dropdown for selecting a bill ID. This enhancement improves the user experience by allowing sellers to easily search and select a specific bill ID when adding return items.
=> feat: Add react-select dependency for dropdown functionality

client/src/components/accountant/AccountantDashboardHome.jsx, client/src/components/seller/DashCustomerReturnItem.jsx
The code changes update the UI of the customer return item dashboard by adding a modal for adding return items and implementing a dropdown functionality using the "react-select" library. This enhances the user experience by providing a more intuitive way to select a bill ID and add return items.
=> feat: Improve UI of customer return item dashboard add way to select bill and retrieve bill detail

client/src/components/seller/DashCustomerReturnItem.jsx
The code changes update the placeholder text for the customer return item dropdown in the `DashCustomerReturnItem` component. The placeholder text was commented out previously, but now it has been updated to "Search and select an item". This improves the clarity and usability of the dropdown for selecting an item when adding return items.
=> feat: Update customer return item dropdown placeholder text

client/src/components/seller/DashCustomerReturnItem.jsx
=> refactor: Simplify handleReturnCountChange function in DashCustomerReturnItem.jsx

client/src/components/seller/DashCustomerReturnItem.jsx
=> Update table header cell label for amount paid to amount refunded in DashCustomerReturnItem.jsx

client/src/components/seller/DashCustomerReturnItem.jsx
=> refactor: Add isSubmitted state and update submit button logic in DashCustomerReturnItem.jsx

client/src/components/DashProducts.jsx, client/src/components/DashSidebar.jsx, client/src/pages/Dashboard.jsx
=> refactor: Hide "Add Product" button for Accountant role in DashProducts.jsx

client/src/components/DashProducts.jsx, client/src/components/DashShops.jsx, client/src/pages/Dashboard.jsx
…
This commit modifies the DashProducts component to hide specific buttons based on the user's role. The buttons that are hidden include the "Add Product" button and certain action buttons for each product. This change improves the user experience by providing a more tailored interface for different user roles, such as Accountant and Director.
=> feat: Update DashProducts component to hide certain buttons based on user role

client/src/components/DashShops.jsx
=> feat: Update DashShops component to hide certain buttons based on user role

client/src/components/DashSaleHistory.jsx, client/src/components/DashSidebar.jsx, client/src/components/seller/DashCustomerReturnItem.jsx, client/src/components/seller/DashPOS.jsx, client/src/pages/Dashboard.jsx
[feat: Add second to formatted time in DashSaleHistory, DashCustomerRe…](https://github.com/FOT-Group-Project/Sabaragamu-Athsalu-Management-System/commit/c7a1dfbae2dc2efd0166d884f72a03f384e6ee78) 
…turnItem, and DashPOS components
=> feat: Add second to formatted time in DashSaleHistory, DashCustomerRe…   …turnItem, and DashPOS components
